In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from random import randint

In [2]:
artists = pd.read_csv("Data/hetrec2011-lastfm-2k/artists.dat", delimiter='\t')
tags = pd.read_csv("Data/hetrec2011-lastfm-2k/tags.dat", delimiter='\t', encoding = "latin-1")
userArt = pd.read_csv("Data/hetrec2011-lastfm-2k/user_artists.dat", delimiter='\t')
userFrd = pd.read_csv("Data/hetrec2011-lastfm-2k/user_friends.dat", delimiter='\t')
userTAT = pd.read_csv("Data/hetrec2011-lastfm-2k/user_taggedartists-timestamps.dat", delimiter='\t')
userTA = pd.read_csv("Data/hetrec2011-lastfm-2k/user_taggedartists.dat", delimiter='\t')

In [3]:
artistlist = []
for i in range(userArt.shape[0]):
    if userArt['artistID'][i] not in artistlist:
        artistlist.append(userArt['artistID'][i])
artistlist.sort()

In [4]:
userlist = []
for i in range(userArt.shape[0]):
    if userArt['userID'][i] not in userlist:
        userlist.append(userArt['userID'][i])

In [5]:
testDF = pd.read_csv("./Data/evaluationMatrix2.csv", index_col=0)

In [6]:
testDF

,0,1,2,3,4,5,6,7,8,9,...,17622,17623,17624,17625,17626,17627,17628,17629,17630,17631
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,587.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,212.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,550.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1862,0.0,83.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1863,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1864,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1865,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1866,0.0,0.0,0.0,0.0,0.0,0.0,399.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1867,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1868,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1869,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1870,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1871,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1872,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1873,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1874,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1875,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1877,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1883,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1884,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1886,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1887,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1888,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1890,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1891,0.0,0.0,408.0,0.0,0.0,404.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
testCP = testDF.copy()

## Método que usa um Knn

In [8]:
nbrs = NearestNeighbors(leaf_size=50, n_neighbors=3).fit(testCP)

In [9]:
distances, indices = nbrs.kneighbors(testCP)

In [10]:
indices

array([[   0, 1686, 1097],
       [   1, 1706, 1708],
       [   2,  528,  461],
       ...,
       [1889, 1005,   98],
       [1890, 1792, 1708],
       [1891,  548,  196]])

In [190]:
testCP2 = testCP.copy()
mylisttest = []
for i in range(17632):
    mylisttest.append(0)
for i in range(20):
    rpos = randint(0,17632)
    #rvalue = randint(0,1000)
    rvalue = i*i
    if i == 19:
        rvalue = 1000
    mylisttest[rpos] = rvalue
mylisttest[45] = 12000
mylisttest[46] = 10000
mylisttest[47] = 8000
mylisttest = pd.DataFrame(list(zip(mylisttest)),columns=['a'])

In [185]:
neighbors = nbrs.kneighbors([mylisttest['a']])
neighbors

(array([[ 15563.912972  ,  16361.0892058 ,  16377.67251474]]),
 array([[1686, 1097,  709]]))

In [194]:
mostSimilarPref = testCP2.T[neighbors[1][0][0]]
mspo = mostSimilarPref.sort_values(ascending=False)
mlto = mylisttest.sort_values(['a'],ascending=False).reset_index()

similars = []
for i in range(len(mylisttest)):
    if mylisttest['a'][i] > 0:
        if mostSimilarPref[i] > 0:
            similars.append(i)
similars

[45]

In [192]:
mlto

       index      a
0         45  12000
1         46  10000
2         47   8000
3       9363   1000
4      12713    324
5       6537    289
6        786    256
7      13442    225
8      13598    196
9       9681    169
10      9959    144
11      7617    121
12     12675    100
13     12611     81
14      6345     64
15      4625     49
16     14350     36
17      3206     25
18     15481     16
19      3868      9
20      4520      4
21      6781      1
22     11767      0
23     11756      0
24     11773      0
25     11755      0
26     11774      0
27     11758      0
28     11754      0
29     11753      0
...      ...    ...
17602   5861      0
17603   5862      0
17604   5863      0
17605   5864      0
17606   5865      0
17607   5866      0
17608   5867      0
17609   5868      0
17610   5869      0
17611   5870      0
17612   5871      0
17613   5872      0
17614   5873      0
17615   5875      0
17616   5890      0
17617   5876      0
17618   5877      0
17619   5878      0
17620   5879      0
17621   5880      0
17622   5881      0
17623   5882      0
17624   5883      0
17625   5884      0
17626   5885      0
17627   5886      0
17628   5887      0
17629   5888      0
17630   5889      0
17631  17631      0

[17632 rows x 2 columns]

In [203]:
recomendationWeight = 0
recomendation = 0
for i in range(len(mostSimilarPref)):
    if mostSimilarPref[i] > recomendationWeight:
        if mostSimilarPref[i] not in similars:
            recomendationWeight = mostSimilarPref[i]
            recomendation = i            
recID = artistlist[int(recomendation)]
artistaRecomendado = "Nenhum"
for i in range(len(artists)):
    if artists['id'][i] == recID:
        artistaRecomendado = artists['name'][i]
        break
artistaRecomendado

'Duran Duran'

## Método que retorna o usuário que possui mais preferências dentre as maiores preferências fornecidas

#### Meio que um brute force, mas dava pra ser ainda mais bruto

In [204]:
testRec = testCP.copy()
testRecAux = []
similars2 = []
for i in range(len(mlto)):
    if mlto['a'][i] > 0:
        testRecAux = testRec.copy()
        testRec = testRec.drop(testRec[testRec[testRec.columns[int(mlto['index'][i])]] < 1].index)
        print(len(testRec))
        if len(testRec) == 0:
            testRec = testRecAux.copy()
        else:
            similars2.append(mlto['index'][i])
    else:
        break
testRec

111
4
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

,0,1,2,3,4,5,6,7,8,9,...,17622,17623,17624,17625,17626,17627,17628,17629,17630,17631
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [205]:
similars2

[45, 46, 47]

In [206]:
testCP3 = testCP.copy()
mostSimilarPref2 = testCP3.T[testRec.index[0]]
recomendation = 0
recomendationWeight = 0
for i in range(len(mostSimilarPref)):
    if mostSimilarPref2[i] > recomendationWeight:
        if mostSimilarPref2[i] not in similars2:
            recomendationWeight = mostSimilarPref2[i]
            recomendation = i
recID = artistlist[int(recomendation)]
artistaRecomendado = "Nenhum"
for i in range(len(artists)):
    if artists['id'][i] == recID:
        artistaRecomendado = artists['name'][i]
        break
artistaRecomendado

'Duran Duran'

## Método mais brute force

In [207]:
ua2 = userArt.copy()
ua2 = ua2.sort_values(['weight'],ascending=False).reset_index(drop=True)
maiorDeTodos = ua2['weight'][0]
ua2 = ua2.groupby(['userID'], sort=False)
ua2.get_group(88)

       userID  artistID  weight
72140      88      1947      94
77274      88      2398      68
78727      88      2399      61
79774      88       859      55
80277      88      2400      53
80507      88       159      52
80635      88      2280      51
82417      88       204      42
82447      88      2401      42
83348      88      2402      38
83877      88       211      35
84125      88       433      34
85041      88      2403      29
85308      88      2404      28
85311      88      2405      28
85393      88       622      28
86234      88      2406      24
86482      88      2407      23
86696      88      2277      22
86846      88      2408      21
88169      88       196      15
88564      88      2409      14
88614      88       440      14
89095      88      1732      12
89096      88       210      12
89106      88      2410      12
89107      88      2411      12
89812      88      2414       9
89813      88      2413       9
89814      88      2412       9
89826      88       629       9
90152      88      2415       8
90186      88      2416       7
90225      88      2417       7
90393      88       199       7
90419      88      1242       7
90719      88      2418       6
90915      88       223       5
90940      88      2420       5
90949      88      2419       5
90952      88      2421       5
90954      88      2422       5
90955      88      2423       5
91413      88      2425       4
91417      88       592       4
91422      88       863       4
91424      88      1944       4
91426      88      2424       4
91514      88       154       3
91517      88       630       3

In [208]:
mlto3 = mlto.copy()
mlto3 = mlto3.drop(mlto3[mlto3['a'] < 1].index)
mlto3

    index      a
0      45  12000
1      46  10000
2      47   8000
3    9363   1000
4   12713    324
5    6537    289
6     786    256
7   13442    225
8   13598    196
9    9681    169
10   9959    144
11   7617    121
12  12675    100
13  12611     81
14   6345     64
15   4625     49
16  14350     36
17   3206     25
18  15481     16
19   3868      9
20   4520      4
21   6781      1

In [233]:
maior = 0
maiorUser = 0
score = 0
tamanho = len(mlto3)
valorMaior = mlto3['a'][0]
valorMenor = mlto3['a'][len(mlto3)-1]
for i in range(len(userlist)):
    score = 0
    cont = 0
    ua3 = ua2.get_group(userlist[i]).copy().reset_index(drop=True)
    ua3 = ua3.sort_values(['weight'],ascending=False).reset_index(drop=True)
    valorRefMaior = ua3['weight'][0]
    for j in range((len(mlto3)-1),-1,-1):
        for k in range(len(ua3)):
            if artistlist[mlto3['index'][j]] == ua3['artistID'][k]:
                cont = cont + 1
                score = score + cont*((ua3['weight'][k]/maiorDeTodos)*((mlto3['a'][j]/maiorDeTodos)))
                if i==0 or i==1103:
                    print(cont)
                    print("score")
                    print(score)
                    
                
    if score > maior:
        print(score)
        maior = score
        maiorUser = i

1
score
0.000729992026915
2
score
0.00260947550737
3
score
0.00662719702031
0.00662719702031
1
score
0.00995049038538
0.00995049038538

In [218]:
maior

0.099504903853776389

In [219]:
maiorUser

1103

In [212]:
userlist[maiorUser]

1210

In [214]:
maiorDeTodos

352698

In [234]:
ua2.get_group(userlist[maiorUser])

       userID  artistID  weight
23       1210        51  103150
158      1210        72   27229
304      1210       159   16739
342      1210       511   15662
626      1210      4313   10034
1302     1210      1014    5635
1334     1210        67    5553
1373     1210       874    5444
1438     1210      2556    5255
1533     1210        77    5057
1548     1210       227    5005
1637     1210        85    4810
1735     1210       599    4628
1760     1210      2562    4583
1771     1210        59    4561
2120     1210       190    4055
2458     1210       193    3633
2467     1210      1013    3624
2606     1210        98    3505
3216     1210       959    3028
3685     1210      6350    2735
3739     1210       997    2710
4258     1210       917    2472
4367     1210      1001    2428
4404     1210      8995    2411
5017     1210       172    2210
5456     1210       155    2082
5619     1210      1892    2029
5948     1210       170    1948
5969     1210       533    1944
6368     1210      3280    1840
6622     1210      1122    1787
6682     1210       187    1777
7558     1210       998    1615
7755     1210      5000    1585
7904     1210      1413    1563
8061     1210     13161    1543
8102     1210       157    1535
8142     1210      1810    1530
8211     1210      3920    1521
8335     1210      2343    1506
8372     1210       732    1500
9044     1210      1076    1413
9171     1210       993    1400
9853     1210      2559    1325
10093    1210      1019    1300
10205    1210       999    1289
10223    1210       996    1287
10253    1210       601    1284
10498    1210      2531    1257

In [215]:
mlto3

    index      a
0      45  12000
1      46  10000
2      47   8000
3    9363   1000
4   12713    324
5    6537    289
6     786    256
7   13442    225
8   13598    196
9    9681    169
10   9959    144
11   7617    121
12  12675    100
13  12611     81
14   6345     64
15   4625     49
16  14350     36
17   3206     25
18  15481     16
19   3868      9
20   4520      4
21   6781      1

In [235]:
ua4 = ua2.get_group(userlist[maiorUser]).copy().reset_index(drop=True)
similars3 = []
for i in range(len(mlto3)):
    for j in range(len(ua4)):
        if artistlist[mlto3['index'][i]] == ua4['artistID'][j]:
            similars3.append(ua4['artistID'][j])
            print(j)

similars3

0

[51]

In [236]:
mlto3['index'][0]

45