In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from random import randint

In [2]:
artists = pd.read_csv("Data/hetrec2011-lastfm-2k/artists.dat", delimiter='\t')
tags = pd.read_csv("Data/hetrec2011-lastfm-2k/tags.dat", delimiter='\t', encoding = "latin-1")
userArt = pd.read_csv("Data/hetrec2011-lastfm-2k/user_artists.dat", delimiter='\t')
userFrd = pd.read_csv("Data/hetrec2011-lastfm-2k/user_friends.dat", delimiter='\t')
userTAT = pd.read_csv("Data/hetrec2011-lastfm-2k/user_taggedartists-timestamps.dat", delimiter='\t')
userTA = pd.read_csv("Data/hetrec2011-lastfm-2k/user_taggedartists.dat", delimiter='\t')

In [3]:
artistlist = []
for i in range(userArt.shape[0]):
    if userArt['artistID'][i] not in artistlist:
        artistlist.append(userArt['artistID'][i])
artistlist.sort()

In [24]:
artistlist

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 30,
 31,
 32,
 34,
 36,
 37,
 38,
 39,
 40,
 41,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 ...]

In [4]:
userlist = []
for i in range(userArt.shape[0]):
    if userArt['userID'][i] not in userlist:
        userlist.append(userArt['userID'][i])

In [38]:
def getPosArtistList(artID):
    for i in range(0,len(artistlist)):
        if artID == artistlist[i]:
            return i
    return -1

def getPosUserList(userID):
    for i in range(0,len(userlist)):
        if userID == userlist[i]:
            return i
    return -1

In [5]:
testDF = pd.read_csv("./Data/evaluationMatrix2.csv", index_col=0)

In [6]:
testDF

,0,1,2,3,4,5,6,7,8,9,...,17622,17623,17624,17625,17626,17627,17628,17629,17630,17631
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,587.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,212.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,550.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1862,0.0,83.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1863,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1864,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1865,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1866,0.0,0.0,0.0,0.0,0.0,0.0,399.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1867,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1868,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1869,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1870,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1871,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1872,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1873,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1874,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1875,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1876,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1877,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1882,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1883,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1884,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1886,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1887,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1888,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1889,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1890,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1891,0.0,0.0,408.0,0.0,0.0,404.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
testCP = testDF.copy()

## Método que usa um Knn

In [44]:
nbrs = NearestNeighbors(leaf_size=50, n_neighbors=3).fit(testCP)

In [46]:
distances, indices = nbrs.kneighbors(testCP)

In [47]:
indices

array([[   0, 1686, 1097],
       [   1, 1706, 1708],
       [   2,  528,  461],
       ...,
       [1889, 1005,   98],
       [1890, 1792, 1708],
       [1891,  548,  196]])

In [48]:
testCP2 = testCP.copy()
mylisttest = []
for i in range(17632):
    mylisttest.append(0)
for i in range(20):
    rpos = randint(0,17632)
    #rvalue = randint(0,1000)
    rvalue = i*i
    if i == 19:
        rvalue = 1000
    mylisttest[rpos] = rvalue
mylisttest[45] = 12000
mylisttest[46] = 10000
mylisttest[47] = 8000
mylisttest = pd.DataFrame(list(zip(mylisttest)),columns=['a'])

In [56]:
def toListTest(tuples):
    myArtists = []
    myValues = []
    cont = 0
    for i in range(len(artistlist)):
        match = 0
        if cont < len(tuples):
            for j in range(len(tuples)):
                if artistlist[i] == tuples[j][0]:
                    myArtists.append(tuples[j][0])
                    myValues.append(tuples[j][1])
                    match = 1
                    cont = cont + 1
        if match == 0:
            myArtists.append(artistlist[i])
            myValues.append(0)
            match = 1
    mylisttest = pd.DataFrame(list(zip(myValues)),columns=['a'])
    return mylisttest

In [66]:
aba = toListTest([(2,10),(3,15),(18745,20)])

In [67]:
neighbors = nbrs.kneighbors([mylisttest['a']])
neighbors

(array([[ 15563.912972  ,  16361.0892058 ,  16375.59150077]]),
 array([[1686, 1097,  709]]))

In [68]:
mostSimilarPref = testCP2.T[neighbors[1][0][0]]
mspo = mostSimilarPref.sort_values(ascending=False)
mlto = mylisttest.sort_values(['a'],ascending=False).reset_index()

similars = []
for i in range(len(mylisttest)):
    if mylisttest['a'][i] > 0:
        if mostSimilarPref[i] > 0:
            similars.append(i)
similars

[45]

In [81]:
def getMostSimilar(listtest):
    neighbors = nbrs.kneighbors(listtest['a'])
    mostSimilarPref = testCP2.T[neighbors[1][0][0]]
    return mostSimilarPref

def getMostSimilarOrd(listtest):
    neighbors = nbrs.kneighbors(listtest['a'])
    mostSimilarPref = testCP2.T[neighbors[1][0][0]]
    mspo = mostSimilarPref.sort_values(ascending=False)
    return mspo

def getListOrd(listtest):
    mlto = listtest.sort_values(['a'],ascending=False).reset_index()
    return mlto

In [231]:
def recKNN(listtest):
    neighbors = nbrs.kneighbors(listtest['a'])
    print("User")
    print(userlist[neighbors[1][0][0]])
    mostSimilarPref = getMostSimilar(listtest)
    similars = []
    for i in range(len(listtest)):
        if listtest['a'][i] > 0:
            if mostSimilarPref[i] > 0:
                similars.append(i)
    
    recomendationWeight = 0
    recomendation = 0
    similarsReal = []
    for i in range(len(similars)):
        similarsReal.append(artistlist[similars[i]])
    print("Similars")
    print(similarsReal)
    for i in range(len(mostSimilarPref)):
        if mostSimilarPref[i] > recomendationWeight:
            if int(mostSimilarPref.index[i]) not in similars:
                recomendationWeight = mostSimilarPref[i]
                recomendation = i            
    recID = artistlist[int(recomendation)]
    artistaRecomendado = "Nenhum"
    for i in range(len(artists)):
        if artists['id'][i] == recID:
            artistaRecomendado = artists['name'][i]
            break
    print("Recommendation")
    return artistaRecomendado

In [152]:
result1 = recKNN(aba)
result1

/Users/ajgan/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/ajgan/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

[]

'Matt Lewis Band'

In [87]:
mlto

       index      a
0         45  12000
1         46  10000
2         47   8000
3       2690   1000
4      14663    324
5       3371    289
6        971    256
7       4310    225
8       2942    196
9        442    169
10       558    144
11      8742    121
12     17185    100
13      6106     81
14      2542     64
15     13667     49
16      9317     36
17       570     25
18       855     16
19       491      9
20      4765      4
21      9515      1
22     11772      0
23     11755      0
24     11754      0
25     11753      0
26     11842      0
27     11757      0
28     11752      0
29     11773      0
...      ...    ...
17602   5867      0
17603   5868      0
17604   5869      0
17605   5870      0
17606   5871      0
17607   5872      0
17608   5873      0
17609   5874      0
17610   5875      0
17611   5876      0
17612   5877      0
17613   5878      0
17614   5879      0
17615   5881      0
17616   5896      0
17617   5882      0
17618   5883      0
17619   5884      0
17620   5885      0
17621   5886      0
17622   5887      0
17623   5888      0
17624   5889      0
17625   5890      0
17626   5891      0
17627   5892      0
17628   5893      0
17629   5894      0
17630   5895      0
17631  17631      0

[17632 rows x 2 columns]

In [150]:
recomendationWeight = 0
recomendation = 0
for i in range(len(mostSimilarPref)):
    if mostSimilarPref[i] > recomendationWeight:
        if int(mostSimilarPref.index[i]) not in similars:
            recomendationWeight = mostSimilarPref[i]
            recomendation = i
recID = artistlist[int(recomendation)]
artistaRecomendado = "Nenhum"
for i in range(len(artists)):
    if artists['id'][i] == recID:
        artistaRecomendado = artists['name'][i]
        break
artistaRecomendado

'Seals & Crofts'

## Método que retorna o usuário que possui mais preferências dentre as maiores preferências fornecidas

#### Meio que um brute force, mas dava pra ser ainda mais bruto

In [91]:
testRec = testCP.copy()
testRecAux = []
similars2 = []
for i in range(len(mlto)):
    if mlto['a'][i] > 0:
        testRecAux = testRec.copy()
        testRec = testRec.drop(testRec[testRec[testRec.columns[int(mlto['index'][i])]] < 1].index)
        if len(testRec) == 0:
            testRec = testRecAux.copy()
        else:
            similars2.append(mlto['index'][i])
    else:
        break
testRec

,0,1,2,3,4,5,6,7,8,9,...,17622,17623,17624,17625,17626,17627,17628,17629,17630,17631
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [92]:
similars2

[45, 46, 47]

In [145]:
testCP3 = testCP.copy()
mostSimilarPref2 = testCP3.T[testRec.index[0]]
recomendation = 0
recomendationWeight = 0
for i in range(len(mostSimilarPref)):
    if mostSimilarPref2[i] > recomendationWeight:
        if int(mostSimilarPref2.index[i]) not in similars2:
            recomendationWeight = mostSimilarPref2[i]
            recomendation = i
recID = artistlist[int(recomendation)]
artistaRecomendado = "Nenhum"
for i in range(len(artists)):
    if artists['id'][i] == recID:
        artistaRecomendado = artists['name'][i]
        break
artistaRecomendado

'Hooverphonic'

In [240]:
def recBrute(listtest):
    mlto = getListOrd(listtest)
    testRec = testCP.copy()
    testRecAux = []
    similars2 = []
    mostSimilarPref = getMostSimilar(listtest)
    for i in range(len(mlto)):
        if mlto['a'][i] > 0:
            testRecAux = testRec.copy()
            testRec = testRec.drop(testRec[testRec[testRec.columns[int(mlto['index'][i])]] < 1].index)
            if len(testRec) == 0:
                testRec = testRecAux.copy()
            else:
                similars2.append(mlto['index'][i])
        else:
            break
            
    testCP3 = testCP.copy()
    mostSimilarPref2 = testCP3.T[testRec.index[0]]
    recomendation = 0
    recomendationWeight = 0
    similarsReal2 = []
    print("User")
    print(userlist[testRec.index[0]])
    for i in range(len(similars2)):
        similarsReal2.append(artistlist[similars2[i]])
    print("Similars")
    print(similarsReal2)
    for i in range(len(mostSimilarPref)):
        if mostSimilarPref2[i] > recomendationWeight:
            if int(mostSimilarPref2.index[i]) not in similars2:
                recomendationWeight = mostSimilarPref2[i]
                recomendation = i
    recID = artistlist[int(recomendation)]
    artistaRecomendado = "Nenhum"
    for i in range(len(artists)):
        if artists['id'][i] == recID:
            artistaRecomendado = artists['name'][i]
            break
    print("Recommendation")
    return artistaRecomendado

In [147]:
result2 = recBrute(aba)
result2

/Users/ajgan/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

'The Kooks'

## Método mais brute force

In [114]:
ua2 = userArt.copy()
ua2 = ua2.sort_values(['weight'],ascending=False).reset_index(drop=True)
maiorDeTodos = ua2['weight'][0]
ua2 = ua2.groupby(['userID'], sort=False)

In [113]:
def getListOrdNotNull(listtest):
    mlto = getListOrd(listtest)
    mlto3 = mlto.copy()
    mlto3 = mlto3.drop(mlto3[mlto3['a'] < 1].index)
    return mlto3

In [115]:
mlto3 = mlto.copy()
mlto3 = mlto3.drop(mlto3[mlto3['a'] < 1].index)
mlto3

    index      a
0      45  12000
1      46  10000
2      47   8000
3    2690   1000
4   14663    324
5    3371    289
6     971    256
7    4310    225
8    2942    196
9     442    169
10    558    144
11   8742    121
12  17185    100
13   6106     81
14   2542     64
15  13667     49
16   9317     36
17    570     25
18    855     16
19    491      9
20   4765      4
21   9515      1

In [116]:
maior = 0
maiorUser = 0
score = 0
tamanho = len(mlto3)
valorMaior = mlto3['a'][0]
valorMenor = mlto3['a'][len(mlto3)-1]
for i in range(len(userlist)):
    score = 0
    cont = 0
    ua3 = ua2.get_group(userlist[i]).copy().reset_index(drop=True)
    ua3 = ua3.sort_values(['weight'],ascending=False).reset_index(drop=True)
    valorRefMaior = ua3['weight'][0]
    for j in range((len(mlto3)-1),-1,-1):
        for k in range(len(ua3)):
            if artistlist[mlto3['index'][j]] == ua3['artistID'][k]:
                cont = cont + 1
                score = score + cont*((ua3['weight'][k]/maiorDeTodos)*((mlto3['a'][j]/maiorDeTodos)))
                if i==0 or i==1103:
                    print(cont)
                    print("score")
                    print(score)
                    
                
    if score > maior:
        maior = score
        maiorUser = i

1
score
0.000729992026915
2
score
0.00260947550737
3
score
0.00662719702031
1
score
2.35789161085e-06
2
score
0.0199033386624

In [117]:
maior

0.019903338662366134

In [118]:
maiorUser

1103

In [119]:
userlist[maiorUser]

1210

In [120]:
maiorDeTodos

352698

In [121]:
ua2.get_group(userlist[maiorUser])

       userID  artistID  weight
23       1210        51  103150
158      1210        72   27229
304      1210       159   16739
342      1210       511   15662
626      1210      4313   10034
1302     1210      1014    5635
1334     1210        67    5553
1373     1210       874    5444
1438     1210      2556    5255
1533     1210        77    5057
1548     1210       227    5005
1637     1210        85    4810
1735     1210       599    4628
1760     1210      2562    4583
1771     1210        59    4561
2120     1210       190    4055
2458     1210       193    3633
2467     1210      1013    3624
2606     1210        98    3505
3216     1210       959    3028
3685     1210      6350    2735
3739     1210       997    2710
4258     1210       917    2472
4367     1210      1001    2428
4404     1210      8995    2411
5017     1210       172    2210
5456     1210       155    2082
5619     1210      1892    2029
5948     1210       170    1948
5969     1210       533    1944
6368     1210      3280    1840
6622     1210      1122    1787
6682     1210       187    1777
7558     1210       998    1615
7755     1210      5000    1585
7904     1210      1413    1563
8061     1210     13161    1543
8102     1210       157    1535
8142     1210      1810    1530
8211     1210      3920    1521
8335     1210      2343    1506
8372     1210       732    1500
9044     1210      1076    1413
9171     1210       993    1400
9853     1210      2559    1325
10093    1210      1019    1300
10205    1210       999    1289
10223    1210       996    1287
10253    1210       601    1284
10498    1210      2531    1257

In [122]:
mlto3

    index      a
0      45  12000
1      46  10000
2      47   8000
3    2690   1000
4   14663    324
5    3371    289
6     971    256
7    4310    225
8    2942    196
9     442    169
10    558    144
11   8742    121
12  17185    100
13   6106     81
14   2542     64
15  13667     49
16   9317     36
17    570     25
18    855     16
19    491      9
20   4765      4
21   9515      1

In [123]:
ua4 = ua2.get_group(userlist[maiorUser]).copy().reset_index(drop=True)
similars3 = []
for i in range(len(mlto3)):
    for j in range(len(ua4)):
        if artistlist[mlto3['index'][i]] == ua4['artistID'][j]:
            similars3.append(ua4['artistID'][j])
            print(j)

similars3

0
13

[51, 2562]

In [124]:
ua4

    userID  artistID  weight
0     1210        51  103150
1     1210        72   27229
2     1210       159   16739
3     1210       511   15662
4     1210      4313   10034
5     1210      1014    5635
6     1210        67    5553
7     1210       874    5444
8     1210      2556    5255
9     1210        77    5057
10    1210       227    5005
11    1210        85    4810
12    1210       599    4628
13    1210      2562    4583
14    1210        59    4561
15    1210       190    4055
16    1210       193    3633
17    1210      1013    3624
18    1210        98    3505
19    1210       959    3028
20    1210      6350    2735
21    1210       997    2710
22    1210       917    2472
23    1210      1001    2428
24    1210      8995    2411
25    1210       172    2210
26    1210       155    2082
27    1210      1892    2029
28    1210       170    1948
29    1210       533    1944
30    1210      3280    1840
31    1210      1122    1787
32    1210       187    1777
33    1210       998    1615
34    1210      5000    1585
35    1210      1413    1563
36    1210     13161    1543
37    1210       157    1535
38    1210      1810    1530
39    1210      3920    1521
40    1210      2343    1506
41    1210       732    1500
42    1210      1076    1413
43    1210       993    1400
44    1210      2559    1325
45    1210      1019    1300
46    1210       999    1289
47    1210       996    1287
48    1210       601    1284
49    1210      2531    1257

In [241]:
def recBruteForce(listtest):
    
    ua2 = userArt.copy()
    ua2 = ua2.sort_values(['weight'],ascending=False).reset_index(drop=True)
    maiorDeTodos = ua2['weight'][0]
    ua2 = ua2.groupby(['userID'], sort=False)
    
    mlto3 = getListOrdNotNull(listtest)
    maior = 0
    maiorUser = 0
    score = 0
    tamanho = len(mlto3)
    valorMaior = mlto3['a'][0]
    valorMenor = mlto3['a'][len(mlto3)-1]
    
    for i in range(len(userlist)):
        score = 0
        cont = 0
        ua3 = ua2.get_group(userlist[i]).copy().reset_index(drop=True)
        ua3 = ua3.sort_values(['weight'],ascending=False).reset_index(drop=True)
        valorRefMaior = ua3['weight'][0]
        for j in range((len(mlto3)-1),-1,-1):
            for k in range(len(ua3)):
                if artistlist[mlto3['index'][j]] == ua3['artistID'][k]:
                    cont = cont + 1
                    score = score + cont*((ua3['weight'][k]/maiorDeTodos)*((mlto3['a'][j]/maiorDeTodos)))
                        
        if score > maior:
            maior = score
            maiorUser = i
            
    ua4 = ua2.get_group(userlist[maiorUser]).copy().reset_index(drop=True)
    similars3 = []
    for i in range(len(mlto3)):
        for j in range(len(ua4)):
            if artistlist[mlto3['index'][i]] == ua4['artistID'][j]:
                similars3.append(ua4['artistID'][j])
    
    print("User")
    print(userlist[maiorUser])
    recomendationWeight = 0
    recomendation = 0
    print("Similars")
    print(similars3)
    for i in range(len(ua4)):
        if ua4['weight'][i] > recomendationWeight:
            if ua4['artistID'][i] not in similars3:
                recomendationWeight = ua4['weight'][i]
                recomendation = i            
    recID = artistlist[int(recomendation)]
    artistaRecomendado = "Nenhum"
    for i in range(len(artists)):
        if artists['id'][i] == recID:
            artistaRecomendado = artists['name'][i]
            break
    print("Recommendation")
    return artistaRecomendado

In [185]:
result3 = recBruteForce(aba)
result3

'Diary of Dreams'

# Passo a passo
- Entrada -> lista de tuplas (artista, peso)
- listtest -> toListTest(Entrada)
- recKNN(listtest) = Recomendação usando KNN
- recBrute(listtest) = Recomendação usando Brute Force método 1
- recBruteForce(listtest) = Recomendação usando Brute Force método 2

# Exemplo

In [242]:
entrada = [(1,100),(10,200),(25,50),(40,500),(50,25)]
entradaListTest = toListTest(entrada)

In [243]:
recKNN(entradaListTest)

/Users/ajgan/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
/Users/ajgan/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

User
438
Similars
[10]
Recommendation

'Tactical Sekt'

In [244]:
recBrute(entradaListTest)

/Users/ajgan/anaconda/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)

User
1352
Similars
[40, 25]
Recommendation

'Herr M.'

In [245]:
recBruteForce(entradaListTest)

User
567
Similars
[40]
Recommendation

'MALICE MIZER'